### ISSUE TITLE
Add User Authentication

### ISSUE THREAD

**Issue by hasanzaidi1** [hasanzaidi1/health_fitness_web_app#5]
### Story: As a user, I want to sign up with email and password
- [x] Design sign-up form UI
- [x] Implement API for sign-up
- [x] Write unit tests for API
- [x] #7 
- [x] get in touch with senior devs
